name: flutter_network_lens
description: An in-app network traffic tracker and inspector for Flutter test and release builds.

version: 0.1.0

homepage: https://github.com/azaadmottan/flutter-network-lens
repository: https://github.com/azaadmottan/flutter-network-lens
issue_tracker: https://github.com/azaadmottan/flutter-network-lens/issues
topics:
  - networking
  - debugging
  - http
  - dio

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.11.1
  get: ^4.7.3
  http: ^1.6.0

  shared_preferences: ^2.3.0
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
